### ISSUE TITLE
Model with fixed effects and pedigree

### ISSUE THREAD

**Issue by volpatoo** [gdlc/BGLR-R#31]
I am trying to fit a model using the BGLR package in R. Unfortunately, I'had not success to do it. I would like to predict plant height using the following BGLR model (dataset with 2 sites, 50 genotypes with pedigree): 
yij = u + Ei + gi(A) + e
yij = are the BLUEs from aerial data and ground data obtained by my "golden model" previously fitted in ASReml software (model with genotype, site, GxE interaction, repetition, and bloc - lattice design).  
Ei= is the fixed effects for sites
gi(A)= random effects for genotype with pedigree (A).

How can I fit a BGLR model using sites with fixed effects and genotype (random) with a pedigree? Could you please provide example in R using the BGLR scripts? 

Thank you very much!

Cheers,

I attached the sample dataset (data_BLUEs) and the pedigree (calculated as twice the coefficient of parentage) as well.
[A.matrix.txt](https://github.com/gdlc/BGLR-R/files/3235386/A.matrix.txt)
[data.txt](https://github.com/gdlc/BGLR-R/files/3235387/data.txt)

Leonardo

**Comment by volpatoo** [comment]
I already figured out this, thanks for this excellent package.

**Comment by gdlc** [comment]
Thanks for you interest in BGLR!

**Comment by wez078** [comment]
I am still struggle to incorporate fixed effects, with BGLR, I would like to add major QTL as fixed effect, not sure how can do this, 
Much appreciate for the help
Sincerely
wentao

**Comment by gdlc** [comment]
Just add to your linear predictor that. Suppose y has your phenotypes, X
your markers, and z the major effect QTL, then run

X=as.matrix(X)
W=as.matrix(W)

fm=BGLR(y=y,ETA=list( MRKS=list(X=X,model='BRR'),
                                       QTL=list(X=W,model='FIXED'))
                 nIter=...)

If you are using a G or A matrix instead of markers directly, you can
change MRKS=(X=X,model='BRR') with MRKS=(K=G,model='RKHS')

There are plenty of examples here

         https://github.com/gdlc/bglr-r

Don't forget to cite,

https://www.genetics.org/content/genetics/198/2/483.full.pdf

if you use BGLR in publications

Gustavo

**Comment by wez078** [comment]
Dear Gustavo:
Many Thanks for your help, I tried, it worked out,
for sure, will cite  your 2014 paper in Genetics (BGLR) for our FHB
genomics prediction MS

Just say, Many Thanks again

Sincerely
wentao
