### ISSUE TITLE
Warm starting the Gibbs sampling

### ISSUE THREAD

**Issue by cruyffturn** [gdlc/BGLR-R#60]
Is there a way to warm start Gibbs sampling with particular initial values? I wasn't sure whether it's possible with adjusting the prior means as it's a hierarchical model.

**Comment by gdlc** [comment]
Unfortunately we have not implemented this, there was an attempt that would
allow you to restore and environment and keep it running but we gave up....

As for disabling the writing of files, I hesitate to implement that in the
general package because the user base is broad and we have not received
such request before.

Note, however, that the files that are heavy are the binary ones and these
are only saved if you sepcify saveEffects=TRUE, if that is not the case
only relatively light *.dat files are saved.


If you want to avoid saving the *.dat files, my suggestion would be to do a
hack. Copy BGLR.R into  BGLR_no_save.R. get into the BGLR function, and
search replace

write(

with

if(!writeFiles) write(


Then when you call BGLR

library(BGLR)
source('BGLR_no_save.R') that will replace the original BGLR function with
your hack and it should run

Gustavo

**Comment by cruyffturn** [comment]
I must have missed setting "saveEffects=FALSE". Thank you for your fast reply and help.
